spring.datasource.url=jdbc:postgresql://dpg-d88vuubeo5us738cap8g-a.oregon-postgres.render.com/assetdb_ifor?sslmode=require

spring.datasource.username=assetdb_ifor_user

spring.datasource.password=DPA7i1MQZUWwg3zvYVuDTqadK8LQzE8z

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}